### PR TITLE
Issue https://github.com/jwtk/jjwt/issues/399 solved: repackaging ext…

### PR DESCRIPTION
**Pull request by gutmox**
Solving issue: https://github.com/jwtk/jjwt/issues/399

### CODE REVIEW

**Comment by gutmox** [comment]
Yes, you're right, it breaks backward compatibility but I felt "just repackaging" is not a huge deal and it wouldn't bother too much current projects using this library; 

The only alternative I see is distributing also, as it was before, a single artefact, so developers who want to use java modules can just import that single artefact with the whole the project.

**Comment by lhazlewood** [comment]
Yeah, we can't break backwards compatibility.  There are hundreds if not thousands of projects that use JJWT.  But the fix is easy - just deprecate the existing ones and add the new ones to the desired package.  Would you be willing to change the PR to do that?

**Comment by Julien-Devin** [comment]
Hi @gutmox,  @lhazlewood, 

I allow myself to relaunch this PR, because we use this jjwt on few projects, and we are blocked, the new projects are all modular and we have the error : 
_java.lang.module.ResolutionException: Module jjwt.api contains package io.jsonwebtoken.io, module jjwt.jackson exports package io.jsonwebtoken.io to jjwt.api_

Do you have any solution ? If not, a resolution time ?

**Comment by lhazlewood** [comment]
@gutmox I wanted to say thanks again for the PR!  However due to the scope of #496 (with backwards compatible shaded jars), that issue superseded this one because it's a superset of this PR's functionality, so we'll be closing this one.  Thank you!

**Pull request closed without merging**
