### PR TITLE
Feat: Added New Tests

### PR DESCRIPTION
**Pull request by Yola21**
Added tests to Collections Test

### CODE REVIEW

**Comment by bdemers** [comment]
It looks like the `htmlReport` folder should not have been checked in, can you remove it?

**Comment by Yola21** [comment]
> It looks like the `htmlReport` folder should not have been checked in, can you remove it?

Yeah, sure. I generated the report but forgot to remove it.

**Comment by lhazlewood** [comment]
@Yola21 thanks for updating the PR!  Looks like there's a minor Groovy-on-JDK7 syntax error.

**Comment by lhazlewood** [comment]
@Yola21 any update?

**Comment by Yola21** [comment]
> @Yola21 any update?

@lhazlewood Yes, I am working on this, was caught up in few other stuff. I will update it soon.

**Comment by lhazlewood** [comment]
@Yola21 no worries, take your time, I just wanted to ensure you were aware of it 😉

**Pull request closed without merging**
