### PR TITLE
Create a CI build and test using GitHub Actions.

### PR DESCRIPTION
**Pull request by carldea**
Utilize GitHub's CI infrastructure to build and test your project on JDKs and different OSes concurrently.

### CODE REVIEW

**Comment by bdemers** [comment]
Nice! Once we drop support for 1.7 (i.e. older versions of Android) we should merge this in!

**Review by bdemers — APPROVED** [review]

**Comment by carldea** [comment]
@bdemers 
Thank you! Glad to be able to contribute to Java JSON Web Token.

**Comment by skjolber** [comment]
Did you consider adding dependency caching to improve build times?

**Comment by lhazlewood** [comment]
@skjolber is that possible? I haven't used GitHub Actions myself yet - but are you saying there's a way to ask GitHub to use previously-used build instances so that the Maven dependency cache is already available on the build machine before a JJWT build kicks off?  (My initial thought is that this wouldn't be allowed because it implies state between builds, which adds a significant complexity to the build infrastructure...)

I could (likely) be misunderstanding your suggestion however 😅

**Comment by carldea** [comment]
> @skjolber is that possible? I haven't used GitHub Actions myself yet - but are you saying there's a way to ask GitHub to use previously-used build instances so that the Maven dependency cache is already available on the build machine before a JJWT build kicks off? (My initial thought is that this wouldn't be allowed because it implies state between builds, which adds a significant complexity to the build infrastructure...)
> 
> I could (likely) be misunderstanding your suggestion however 😅

Yes, it's possible as the GitHub infrastructure can cache maven .m2 directory and hash your pom.xmls, if they change it invalidates the cache: 
https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies 

That could be another PR add this capability.

**Comment by lhazlewood** [comment]
Resolved via aa17d5094e70ef628e78ba58c8122cc7a6846635 - Thank you!

**Pull request closed without merging**
