### PR TITLE
add osgi support via maven-bundle-plugin

### PR DESCRIPTION
**Pull request by enflout**
I have tested jjwt as bundle in Equinox Kepler SR1 and it is completely okay! Bundle is resolved:

    59      RESOLVED    io.jsonwebtoken.jjwt_0.5.0.SNAPSHOT

This code:

    byte[] key = new byte[64];
    new SecureRandom().nextBytes(key);
    
    String compact = Jwts.builder().setSubject("Joe").signWith(SignatureAlgorithm.HS256, key).compact();
    
    if (Jwts.parser().setSigningKey(key).parseClaimsJws(compact).getBody().getSubject().equals("Joe")) {
        System.out.println("Jjwt is okay");
    }

And it prints as expected:

    Jjwt is okay

In continue of https://github.com/jwtk/jjwt/issues/19

### CODE REVIEW

**Comment by lhazlewood** [comment]
Thanks for the PR!

**Comment by lhazlewood** [comment]
@enflout  There is no need to specify OSGi package name/metadata?

**Comment by enflout** [comment]
@lhazlewood I think no, it generates automatically by your pom.xml. After 

    mvn clean package

we can see such a MANIFEST.MF:

    Manifest-Version: 1.0
    Export-Package: io.jsonwebtoken;uses:="io.jsonwebtoken.lang,javax.cryp
 to.spec";version="0.5.0.SNAPSHOT",io.jsonwebtoken.lang;uses:="org.slf
 4j";version="0.5.0.SNAPSHOT"
    Implementation-Title: JSON Web Token support for the JVM
    Implementation-Version: 0.5-SNAPSHOT
    Built-By: Orlov_I
    Tool: Bnd-1.43.0
    Bundle-Name: JSON Web Token support for the JVM
    Created-By: Apache Maven Bundle Plugin
    Implementation-Vendor-Id: io.jsonwebtoken
    Bundle-Version: 0.5.0.SNAPSHOT
    Build-Jdk: 1.7.0_67
    Bnd-LastModified: 1429891114864
    Bundle-ManifestVersion: 2
    Specification-Title: JSON Web Token support for the JVM
    Bundle-License: http://www.apache.org/licenses/LICENSE-2.0
    Bundle-Description: chelps open source projects to set up Mave
 n repositories on https://oss.sonatype.org/
    Import-Package: com.fasterxml.jackson.core;version="[2.4,3)",com.faste
 rxml.jackson.databind;version="[2.4,3)",io.jsonwebtoken.lang,javax.cr
 ypto,javax.crypto.spec,javax.xml.bind,org.slf4j;version="[1.7,2)"
    Bundle-SymbolicName: io.jsonwebtoken.jjwt
    Specification-Version: 0.5-SNAPSHOT
    Archiver-Version: Plexus Archiver

If you prefer to override some of this values please let me know and I will put required changes in the PR.

**Comment by lhazlewood** [comment]
@enflout as long as it works, then I'm fine with your modifications.  

However, please do update the Maven plugin to use the latest stable version - we always want to use the latest stable before doing a release.  Also, please define that version as a property in the <properties> section so that a plugin upgrade is as simple as changing that one property.

**Pull request merged**
